name: Deploy to EC2

on:
   workflow_run:
    workflows: ["Build and Push Docker Images"]  # The exact name of the build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
            sudo docker pull awali016/backend-app:GHWF
            sudo docker pull awali016/frontend-app:GHWF

            sudo docker stop backend || true && docker rm backend || true
            sudo docker stop frontend || true && docker rm frontend || true

            sudo docker network inspect myapp-network >/dev/null 2>&1 || docker network create myapp-network

            sudo docker run -d --name backend --network myapp-network -p 8080:8080 awali016/backend-app:GHWF
            sudo docker run -d --name frontend --network myapp-network -p 3000:80 awali016/frontend-app:GHWF
          EOF
