name: Deploy to EC2

on:
   workflow_run:
    workflows: ["Build and Push Docker Images"]  # The exact name of the build workflow
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to EC2 and Deploy Containers
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Log in to Docker
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Pull latest images
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:GHWF
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-app:GHWF

            # Stop and remove existing containers if they exist
            docker stop backend || true && docker rm backend || true
            docker stop frontend || true && docker rm frontend || true
            docker stop postgres || true && docker rm postgres || true

            # Create Docker network if it doesn't exist
            docker network inspect myapp-network >/dev/null 2>&1 || docker network create myapp-network

            # Start PostgreSQL container
            docker run -d \
              --name postgres \
              --network myapp-network \
              -e POSTGRES_USER=${{ secrets.POSTGRES_USER }} \
              -e POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e POSTGRES_DB=${{ secrets.POSTGRES_DB }} \
              -v pgdata:/var/lib/postgresql/data \
              -p 5432:5432 \
              postgres:17

            # Start backend container
            docker run -d \
              --name backend \
              --network myapp-network \
              -p 8080:8080 \
              -e PG_HOST=postgres \
              -e PG_PORT=5432 \
              -e PG_USER=${{ secrets.POSTGRES_USER }} \
              -e PG_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} \
              -e PG_DATABASE=${{ secrets.POSTGRES_DB }} \
              -e DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}?schema=public \
              ${{ secrets.DOCKER_HUB_USERNAME }}/backend-app:GHWF

            # Start frontend container
            docker run -d \
              --name frontend \
              --network myapp-network \
              -p 3000:80 \
              -e REACT_APP_SERVER_API_URL=http://backend:8080 \
              ${{ secrets.DOCKER_HUB_USERNAME }}/frontend-app:GHWF

